### ISSUE TITLE
facing problem using tensorboard

### ISSUE THREAD

**Issue by dnabanita7** [JuliaReinforcementLearning/JuliaReinforcementLearning.github.io#6]
I am facing the following problem while running ``(base) nabanita07@nabanita07:~$ tensorboard --logdir /home/nabanita07/checkpoints/JuliaRL_BasicDQN_CartPole_20200807180019/tb_log``

```
/home/nabanita07/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/nabanita07/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/nabanita07/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/nabanita07/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/nabanita07/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/nabanita07/.local/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/home/nabanita07/anaconda3/bin/tensorboard", line 6, in <module>
    from tensorboard.main import run_main
  File "/home/nabanita07/anaconda3/lib/python3.7/site-packages/tensorboard/main.py", line 40, in <module>
    from tensorboard import default
  File "/home/nabanita07/anaconda3/lib/python3.7/site-packages/tensorboard/default.py", line 39, in <module>
    from tensorboard.plugins.beholder import beholder_plugin_loader
  File "/home/nabanita07/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/__init__.py", line 22, in <module>
    from tensorboard.plugins.beholder.beholder import Beholder
  File "/home/nabanita07/anaconda3/lib/python3.7/site-packages/tensorboard/plugins/beholder/beholder.py", line 199, in <module>
    class BeholderHook(tf.estimator.SessionRunHook):
  File "/home/nabanita07/.local/lib/python3.7/site-packages/tensorflow/python/util/deprecation_wrapper.py", line 106, in __getattr__
    attr = getattr(self._dw_wrapped_module, name)
AttributeError: module 'tensorflow' has no attribute 'estimator'
```

In an alternative to using tensorboard for logging, we can use [TensorBoardLogger.jl](https://github.com/PhilipVinc/TensorBoardLogger.jl) for making it more Julian.

**Comment by findmyway** [comment]
Could you share your tensorboard version and tensorflow version?

It seems to be caused by version mismatch of tensorboard and tensorflow based on the issue here https://github.com/tensorflow/tensorboard/issues/2676 Try to reinstall?

> In an alternative to using tensorboard for logging, we can use TensorBoardLogger.jl for making it more Julian.

Actually this package is using TensorBoardLogger.jl. 😃

**Comment by dnabanita7** [comment]
> Actually this package is using TensorBoardLogger.jl. :smiley: 

That is great!

> It seems to be caused by version mismatch of tensorboard and tensorflow

Yes, that was the problem and also add removing all tensorflow, tensorboard from site-packages if installed with conda.
